# Generated by Django 4.2.1 on 2023-06-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_username_alter_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='type',
            field=models.CharField(default='Not Specified', max_length=200),
        ),
    ]
