# Generated by Django 4.2.1 on 2023-05-23 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExporterLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exporter', models.ForeignKey(limit_choices_to={'group__name': 'Exporter'}, on_delete=django.db.models.deletion.CASCADE, related_name='exporter_licenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
