# Generated by Django 4.2.1 on 2023-05-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_exporterlicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='operation_scale',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
