# Generated by Django 4.2.1 on 2023-05-26 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_farmer_operation_scale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmer',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterField(
            model_name='batch',
            name='buyer',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'Buyer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batch',
            name='exporter',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'Exporter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exporter_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
