# Generated by Django 4.2.1 on 2023-07-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_batch_batch_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='date_sold_to_buyer',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='date_sold_to_exporter',
            field=models.DateField(blank=True, null=True),
        ),
    ]
