# Generated by Django 4.2.1 on 2023-05-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_batch_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='moisture_content',
            field=models.FloatField(default=0.0),
        ),
    ]
