# Generated by Django 4.2.1 on 2023-07-06 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_batch_date_sold_to_buyer_batch_date_sold_to_exporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
    ]
