# Generated by Django 4.2.1 on 2023-05-22 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_cooperative_exporter_delete_exporterlicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='cooperative',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'Cooperative'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
