# Generated by Django 4.2.1 on 2023-05-22 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_cooperative_cooperative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperative',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='exporter',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AddField(
            model_name='cooperative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooperative',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
