# Generated by Django 4.2.1 on 2023-05-27 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_cooperative_options_alter_exporter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterField(
            model_name='exporter',
            name='exporter',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'Exporter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exporter_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
